In [2]:
import numpy as np
import sys



In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

In [ ]:
a.shape

In [ ]:
#Get a specific element [r,c]
a[1, -2]

In [ ]:
#Get a specific row
a[0, :]

In [ ]:
a[:, 3]

In [ ]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

In [ ]:
a[1,5] = 20
print(a)

In [ ]:
a[:, 2] = [5,11]
a

In [ ]:
d = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
d

In [ ]:
#Get specific element (work outside in)
d[0, 1, 1]

In [ ]:
d[:,1,:]

In [ ]:
# replace
d [:, 1, :] = [[4,10], [32,44]]
d

In [52]:
#All 0 matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.ones((4,2,2), dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [55]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [56]:
#Random decimal numbers
np.random.rand(4, 2)

array([[0.10841595, 0.54523368],
       [0.62953992, 0.88967879],
       [0.61927106, 0.70246036],
       [0.27397238, 0.76766543]])

In [59]:
np.random.randint(4,7, size=(3,3))

array([[5, 4, 4],
       [6, 6, 6],
       [5, 4, 6]])

In [6]:
e = np.ones([5,5], dtype = 'int8')
e

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [8]:
e[1:-1, 1:-1] = 0
e

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [9]:
e[2,2] = 9
e

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [10]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


In [11]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
a+2

array([3, 4, 5, 6])

In [13]:
a-2

array([-1,  0,  1,  2])

In [14]:
a*2

array([2, 4, 6, 8])

In [15]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [16]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])